/**
 * @module teams-ai
 */
/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import { TurnContext } from 'botbuilder-core';
import { AI, ConfiguredAIOptions } from './AI';
import { DefaultTurnState } from './DefaultTurnStateManager';
import { Moderator } from './Moderator';
import { Plan } from './Planner';
import { PromptTemplate } from './Prompts';
import { TurnState } from './TurnState';

/**
 * Default moderator created by the AI system if one isn't configured.
 * @summary
 * The default moderator is a pass-through and always approves all inputs and outputs.
 * @template TState Optional. The Application's turn state.
 */
export class DefaultModerator<TState extends TurnState = DefaultTurnState> implements Moderator<TState> {
    /**
     * Allows all prompts by returning undefined.
     * @param context The context object for the turn.
     * @param state The current turn state.
     * @returns A promise that resolves to undefined.
     */
    public reviewInput(
        context: TurnContext,
        state: TState,
    ): Promise<Plan | undefined> {
        // Just allow prompt
        return Promise.resolve(undefined);
    }

    /**
     * Allows all plans by returning the plan as-is.
     * @param context Context for the current turn of conversation.
     * @param state Application state for the current turn of conversation.
     * @param plan Plan generated by the planner.
     * @returns A promise that resolves to the plan.
     */
    public reviewOutput(
        context: TurnContext,
        state: TState,
        plan: Plan
    ): Promise<Plan> {
        // Just approve generated plan
        return Promise.resolve(plan);
    }
}
