// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

/*
All of these responses where generated by GPT using a prompt similar to:

```
Here's a JavaScript string literal template:

`I couldn't find a ${item} on your ${list} list.`

Create a JavaScript array with 7 variations of the template.
The variations should be helpful, creative, clever, and very friendly.
The variations should always use the back tick `` syntax.
The variations should always include ${item} and ${list} variables.
```

7 variations were asked for so that we can remove the 2 we like the least.
*/

export function moveBlocked(): string {
    return getRandomResponse([
        `As you begin heading towards your new destination a mysterious force transports back to your current location.`,
        `As you take the first steps towards what lies ahead, a strange power brings you back to where you started.`,
        `A mysterious source blocks your path to the next location and teleports you back to your where you're at.`,
        `You begin making your way towards the new destination when an unexplainable force drags you back to your current location.`,
        `Trust me. You are not ready to go there yet.`
    ]);
}

export function emptyInventory(): string {
    return getRandomResponse([
        `It looks like you don't have any items on you.`,
        `It appears your inventory is devoid of any items.`,
        `Your inventory is completely empty.`,
        `You don't appear to have anything on you.`,
        `You have nothing in your pockets or in your bag.`,
    ]);
}

export function emptyDropped(): string {
    return getRandomResponse([
        `You see nothing on the ground.`,
        `A quick scan of the area reveals nothing at your feet.`,
        `The immediate area is empty.`,
        `There's nothing here you can take. `,
        `You can't see anything that can be picked up.`,
    ]);
}

export function notDropped(name: string): string {
    return getRandomResponse([
        `There isn't a ${name} nearby.`,
        `There isn't a ${name} on the ground.`,
        `Sorry, there's no ${name} here.`,
        `It appears that a ${name} is nowhere to be seen.`,
        `I'm sorry, but nothing like a ${name} can be found.`
    ]);
}

export function notInInventory(name: string): string {
    return getRandomResponse([
        `You aren't carrying a ${name}`,
        `It doesn't look like you have a ${name}.`,
        `You can't seem to locate a ${name} in your inventory.`,
        `Unfortunately your inventory does not have a ${name}.`,
        `I'm sorry, you don't appear to have a ${name} with you.`
    ]);
}

export function notEnoughGold(gold: number): string {
    if (gold > 0) {
        return getRandomResponse([
            `You take a deep breath as you count your golden coins. Only ${gold}. You're short!`,
            `You check your bag of coins - only ${gold}! A disappointingly paltry sum.`,
            `You empty your bag of coins, only to find ${gold} gold pieces. Far too few.`,
            `You sift through your bag, barely any coins. ${gold}. That wouldn't buy hardly anything of value.`,
            `With a sigh, you count the coins in your bag. Just ${gold} gold pieces, not enough.`
        ]);
    } else {
        return getRandomResponse([
            `As soon as you reach into your bag of gold coins, you can feel that something has gone seriously wrong; all your coins are gone! It looks like you've been robbed!`,
            `You can barely believe your eyes - all the gold coins you had in your bag are gone! Could someone have stolen them?`,
            `Your worst fears are realized when you open your bag of gold coins; empty :(`,
            `You take out your bag of gold coins, only to find that it's empty!`,
            `You search frantically for your bag of gold coins, but it's no where to be found.`
        ]);
    }
}

export function directionNotAvailableExample(direction: string): string {
    return `Player: go ${direction}\n` + 
        getRandomResponse([
            `DM: You can't go ${direction}}.\n`,
            `DM: There's nothing to the ${direction}.\n`,
            `DM: Travel to the ${direction} isn't possible.\n`
        ]);
}

export function dataError(): string {
    return getRandomResponse([
            `Uh oh, it looks like we've got a bit of a hiccup here. Let's try that again.`,
            `Oopsie! That didn't quite go as planned. Let's give it another go.`,
            `Oops... There was a glitch in the matrix. Let's try that again.`,
            `Pardon the interruption! Let's reload and give this another attempt.`,
            `Wow, that was unexpected! Let's do that one over.`
    ]);
}

export function unknownAction(action: string): string {
    return getRandomResponse([
        `I'm sorry, I'm not sure how to ${action}.`,
        `I don't know the first thing about ${action}.`,
        `I'm not sure I'm the best person to help with ${action}.`,
        `I'm still learning about ${action}, but I'll try my best.`,
        `I'm afraid I'm not experienced enough with ${action}.`
    ]);
}

function getRandomResponse(responses: string[]): string {
    const i = Math.floor(Math.random() * (responses.length - 1));
    return responses[i];
}
