// Auto-generated by scripts/sync-devblogs.ts — do not edit manually
export const externalBlogUrls: Record<string, string> = {
    'build-your-own-apps-copilot-on-microsoft-teams-with-the-new-teams-ai-library': 'https://devblogs.microsoft.com/microsoft365dev/build-your-own-apps-copilot-on-microsoft-teams-with-the-new-teams-ai-library/',
    'building-the-next-era-of-ai-teams-ai-library-and-api-message-extensions-ignite-2023': 'https://devblogs.microsoft.com/microsoft365dev/building-the-next-era-of-ai-teams-ai-library-and-api-message-extensions-ignite-2023/',
    'the-future-of-collaboration-and-ai-opportunities-for-partners-in-the-microsoft-teams-ai-ecosystem': 'https://devblogs.microsoft.com/microsoft365dev/the-future-of-collaboration-and-ai-opportunities-for-partners-in-the-microsoft-teams-ai-ecosystem/',
    'a-pro-code-guide-to-build-your-custom-copilot-faster': 'https://devblogs.microsoft.com/microsoft365dev/a-pro-code-guide-to-build-your-custom-copilot-faster/',
    'roadmap-to-empowering-your-workforce-with-ai-how-moodys-copilot-ignited-ai-innovation': 'https://devblogs.microsoft.com/microsoft365dev/roadmap-to-empowering-your-workforce-with-ai-how-moodys-copilot-ignited-ai-innovation/',
    'the-present-and-future-of-copilot-extensibility-top-10-takeaways-from-build-2024': 'https://devblogs.microsoft.com/microsoft365dev/the-present-and-future-of-copilot-extensibility-top-10-takeaways-from-build-2024/',
    'join-the-microsoft-365-copilot-developer-camp': 'https://devblogs.microsoft.com/microsoft365dev/join-the-microsoft-365-copilot-developer-camp/',
    'announcing-the-updated-teams-ai-library-and-mcp-support': 'https://devblogs.microsoft.com/microsoft365dev/announcing-the-updated-teams-ai-library-and-mcp-support/',
    'python-support-for-the-microsoft-teams-sdk-is-now-generally-available': 'https://devblogs.microsoft.com/microsoft365dev/python-support-for-the-microsoft-teams-sdk-is-now-generally-available/',
    'build-collaborative-agents-where-work-happens': 'https://devblogs.microsoft.com/microsoft365dev/build-collaborative-agents-where-work-happens/',
    'whats-new-in-microsoft-teams--may-2026---build-edition': 'https://techcommunity.microsoft.com/blog/microsoftteamsblog/whats-new-in-microsoft-teams--may-2026---build-edition/4524613',
};
