import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

export default {
  default: [{ type: 'autogenerated', dirName: '.' }],
  typescript: [{ type: 'autogenerated', dirName: '.' }],
  csharp: [{ type: 'autogenerated', dirName: '.' }],
} satisfies SidebarsConfig;
