"use strict";
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
Object.defineProperty(exports, "__esModule", { value: true });
exports.offTopic = exports.unknownAction = exports.noListsFound = exports.itemFound = exports.itemNotFound = void 0;
/*
All of these responses where generated by GPT using a prompt similar to:

```
Here's a JavaScript string literal template:
 
`I couldn't find a ${item} on your ${list} list.`

Create a JavaScript array with 7 variations of the template.
The variations should be helpful, creative, clever, and very friendly.
The variations should always use the back tick `` syntax.
The variations should always include ${item} and ${list} variables.
```

7 variations were asked for so that we can remove the 2 we like the least.
*/
function itemNotFound(list, item) {
    return getRandomResponse([
        `I'm sorry, I couldn't locate a ${item} on your ${list} list.`,
        `I don't see a ${item} on your ${list} list.`,
        `It looks like you don't have a ${item} on your ${list} list.`,
        `I'm sorry, I don't see a ${item} on your ${list} list.`,
        `I couldn't find a ${item} listed on your ${list} list.`
    ]);
}
exports.itemNotFound = itemNotFound;
function itemFound(list, item) {
    return getRandomResponse([
        `I found ${item} in your ${list} list.`,
        `It looks like ${item} is in your ${list} list.`,
        `You have a ${item} in your ${list} list.`,
        `The ${item} was found in your ${list} list.`,
        `A ${item} appears to be in your ${list} list.`
    ]);
}
exports.itemFound = itemFound;
function noListsFound() {
    return getRandomResponse([
        `You don't have any lists yet.`,
        `You haven't made any lists yet.`,
        `It looks like you don't have any lists yet.`,
        `No lists have been made yet.`,
        `You don't have any lists set up yet.`
    ]);
}
exports.noListsFound = noListsFound;
function unknownAction(action) {
    return getRandomResponse([
        `I'm sorry, I'm not sure how to ${action}.`,
        `I don't know the first thing about ${action}.`,
        `I'm not sure I'm the best person to help with ${action}.`,
        `I'm still learning about ${action}, but I'll try my best.`,
        `I'm afraid I'm not experienced enough with ${action}.`,
    ]);
}
exports.unknownAction = unknownAction;
function offTopic() {
    return getRandomResponse([
        `I'm sorry, I'm not sure I can help you with that.`,
        `I'm sorry, I'm afraid I'm not allowed to talk about such things.`,
        `I'm sorry, I'm not sure I'm the right person to help you with that.`,
        `I wish I could help you with that, but it's not something I can talk about.`,
        `I'm sorry, I'm not allowed to discuss that topic.`
    ]);
}
exports.offTopic = offTopic;
function getRandomResponse(responses) {
    const i = Math.floor(Math.random() * (responses.length - 1));
    return responses[i];
}
//# sourceMappingURL=responses.js.map