trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - js
    - pipelines/javascript.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node'

- script: 'npm i -g yarn'
  displayName: 'Install Yarn'

- script: 'yarn'
  workingDirectory: 'js'
  displayName: 'Install Dependencies'

- script: 'yarn build'
  workingDirectory: 'js'
  displayName: 'Build'

- script: 'yarn test:nyc:report'
  workingDirectory: 'js'
  displayName: 'Test'

- script: 'yarn lint'
  workingDirectory: 'js'
  displayName: 'Lint'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
      js/packages/teams-ai/*
      js/packages/teams-ai/src/*
      js/packages/teams-ai/lib/*
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)/js/packages/teams-ai'
    ArtifactName: Packages

# - task: Npm@1
#   displayName: 'Publish'
#   continueOnError: true
#   inputs:
#     command: publish
#     workingDir: '$(Build.ArtifactStagingDirectory)/js/packages/teams-ai'
#     publishRegistry: useFeed
#     publishFeed: 'Github_Pipelines/Teams'
