trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - python
    - pipelines/python.yml

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install poetry
    python scripts/install.py
  displayName: 'Install Dependencies'
  workingDirectory: 'python'

- script: |
    python scripts/check.py
  displayName: 'Check'
  workingDirectory: 'python'

- script: |
    python scripts/build.py
  displayName: 'Build'
  workingDirectory: 'python'

- script: |
    python scripts/test.py
  displayName: 'Test'
  workingDirectory: 'python'

- script: |
    python scripts/lint.py
  displayName: 'Lint'
  workingDirectory: 'python'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
      python/packages/ai/dist/*
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)/python/packages/ai'
    ArtifactName: Packages