using Azure.AI.OpenAI;
using Azure.AI.OpenAI.Chat;
using Microsoft.Bot.Schema;
using Microsoft.Teams.AI.Exceptions;
using Microsoft.Teams.AI.Utilities;
using OpenAI.Chat;
using OAI = OpenAI;

namespace Microsoft.Teams.AI.AI.Models
{
    /// <summary>
    /// Represents a message that will be passed to the Chat Completions API
    /// </summary>
    public class ChatMessage
    {
        /// <summary>
        /// The role associated with this message payload.
        /// </summary>
        public ChatRole Role { get; set; }

        /// <summary>
        /// The text associated with this message payload.
        /// </summary>
        public object? Content;

        /// <summary>
        /// The name of the author of this message. `name` is required if role is `function`, and it should be the name of the
        /// function whose response is in the `content`. May contain a-z, A-Z, 0-9, and underscores, with a maximum length of
        /// 64 characters.
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// The name and arguments of a function that should be called, as generated by the model.
        /// </summary>
        public FunctionCall? FunctionCall { get; set; }

        /// <summary>
        /// The ID of the tool call resolved by the provided content. `toolCallId` is required if role is `tool`.
        /// </summary>
        public string? ToolCallId { get; set; }

        /// <summary>
        /// The context used for this message.
        /// </summary>
        public MessageContext? Context { get; set; }

        /// <summary>
        /// The tool calls generated by the model, such as function calls.
        /// </summary>
        public IList<ChatCompletionsToolCall>? ToolCalls { get; set; }

        /// <summary>
        /// Attachments for the bot to send back.
        /// </summary>
        public List<Attachment>? Attachments { get; set; }

        /// <summary>
        /// Gets the content with the given type.
        /// Will throw an exception if the content is not of the given type.
        /// </summary>
        /// <returns>The content.</returns>
        public TContent GetContent<TContent>()
        {
            return (TContent)Content!;
        }

        /// <summary>
        /// Initializes a new instance of ChatMessage.
        /// </summary>
        /// <param name="role"> The role associated with this message payload. </param>
        public ChatMessage(ChatRole role)
        {
            this.Role = role;
        }

        /// <summary>
        /// Initializes a new instance of ChatMessage using OpenAI.Chat.ChatCompletion.
        /// </summary>
        /// <param name="chatCompletion"></param>
        internal ChatMessage(ChatCompletion chatCompletion)
        {
            this.Role = ChatRole.Assistant;
            this.Content = chatCompletion.Content[0].Text;

            if (chatCompletion.FunctionCall != null && chatCompletion.FunctionCall.FunctionName != string.Empty)
            {
                this.Name = chatCompletion.FunctionCall.FunctionName;
                this.FunctionCall = new FunctionCall(chatCompletion.FunctionCall.FunctionName, chatCompletion.FunctionCall.FunctionArguments);
            }

            if (chatCompletion.ToolCalls != null && chatCompletion.ToolCalls.Count > 0)
            {
                this.ToolCalls = new List<ChatCompletionsToolCall>();
                foreach (ChatToolCall toolCall in chatCompletion.ToolCalls)
                {
                    this.ToolCalls.Add(ChatCompletionsToolCall.FromChatToolCall(toolCall));
                }
            }

#pragma warning disable AOAI001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
            AzureChatMessageContext? azureContext = chatCompletion.GetAzureMessageContext();
#pragma warning restore AOAI001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
            if (azureContext != null)
            {
                MessageContext? context = new(azureContext);
                if (context != null)
                {
                    this.Context = context;
                }
            }
        }

        internal OAI.Chat.ChatMessage ToOpenAIChatMessage()
        {
            Verify.NotNull(this.Content);
            Verify.NotNull(this.Role);

            ChatRole role = this.Role;
            OAI.Chat.ChatMessage? message = null;

            string? content = null;
            List<ChatMessageContentPart> contentItems = new();

            // Content is a text
            if (this.Content is string textContent)
            {
                content = textContent;
            }
            else if (this.Content is IEnumerable<MessageContentParts> contentParts)
            {
                // Content is has multiple possibly multi-modal parts.
                foreach (MessageContentParts contentPart in contentParts)
                {
                    if (contentPart is TextContentPart textPart)
                    {
                        contentItems.Add(ChatMessageContentPart.CreateTextMessageContentPart(textPart.Text));
                    }
                    else if (contentPart is ImageContentPart imagePart)
                    {
                        contentItems.Add(ChatMessageContentPart.CreateImageMessageContentPart(new Uri(imagePart.ImageUrl)));
                    }
                }
            }

            // Different roles map to different classes
            if (role == ChatRole.User)
            {
                UserChatMessage userMessage;
                if (content != null)
                {
                    userMessage = new(content);
                }
                else
                {
                    userMessage = new(contentItems);
                }

                if (this.Name != null)
                {
                    // TODO: Currently no way to set `ParticipantName` come and change it eventually.
                    //userMessage.ParticipantName = this.Name;
                }

                message = userMessage;
            }

            if (role == ChatRole.Assistant)
            {
                AssistantChatMessage assistantMessage;

                if (this.FunctionCall != null)
                {
                    ChatFunctionCall functionCall = new(this.FunctionCall.Name ?? "", this.FunctionCall.Arguments ?? "");
                    assistantMessage = new AssistantChatMessage(functionCall, this.GetContent<string>());
                }
                else if (this.ToolCalls != null)
                {
                    List<ChatToolCall> toolCalls = new();
                    foreach (ChatCompletionsToolCall toolCall in this.ToolCalls)
                    {
                        toolCalls.Add(toolCall.ToChatToolCall());
                    }
                    assistantMessage = new AssistantChatMessage(toolCalls, this.GetContent<string>());
                }
                else
                {
                    assistantMessage = new AssistantChatMessage(this.GetContent<string>());
                }

                if (this.Name != null)
                {
                    // TODO: Currently no way to set `ParticipantName` come and change it eventually.
                    // assistantMessage.ParticipantName = this.Name;
                }

                message = assistantMessage;
            }

            if (role == ChatRole.System)
            {
                SystemChatMessage systemMessage = new(this.GetContent<string>());

                if (this.Name != null)
                {
                    // TODO: Currently no way to set `ParticipantName` come and change it eventually.
                    // systemMessage.ParticipantName = chatMessage.Name;
                }

                message = systemMessage;
            }

            if (role == ChatRole.Function)
            {
                // TODO: Clean up
#pragma warning disable CS0618 // Type or member is obsolete
                message = new FunctionChatMessage(this.Name ?? "", this.GetContent<string>());
#pragma warning restore CS0618 // Type or member is obsolete
            }

            if (role == ChatRole.Tool)
            {

                message = new ToolChatMessage(this.ToolCallId ?? "", this.GetContent<string>());
            }

            if (message == null)
            {
                throw new TeamsAIException($"Invalid chat message role: {role}");
            }

            return message;
        }
    }

    /// <summary>
    /// The name and arguments of a function that should be called, as generated by the model.
    /// </summary>
    public class FunctionCall
    {
        /// <summary>
        /// The name of the function to call.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// The arguments to call the function with, as generated by the model in JSON format.
        /// Note that the model does not always generate valid JSON, and may hallucinate parameters
        /// not defined by your function schema. Validate the arguments in your code before calling
        /// your function.
        /// </summary>
        public string Arguments { get; set; } = string.Empty;

        /// <summary>
        /// Creates an instance of `FunctionCall`.
        /// </summary>
        /// <param name="name">function name</param>
        /// <param name="arguments">function arguments</param>
        public FunctionCall(string name, string arguments)
        {
            this.Name = name;
            this.Arguments = arguments;
        }
    }

    /// <summary>
    /// Represents the ChatMessage content.
    /// </summary>
    public abstract class MessageContentParts
    {
        /// <summary>
        /// The type of message content.
        /// </summary>
        public string Type { get; }

        /// <summary>
        /// The chat message content.
        /// </summary>
        /// <param name="type"></param>
        public MessageContentParts(string type)
        {
            this.Type = type;
        }
    }

    /// <summary>
    /// The image content part of the ChatMessage
    /// </summary>
    public class TextContentPart : MessageContentParts
    {
        /// <summary>
        /// The constructor
        /// </summary>
        public TextContentPart() : base("text") { }

        /// <summary>
        /// The text of the message
        /// </summary>
        public string Text = string.Empty;
    }

    /// <summary>
    /// The image content part of the ChatMessage
    /// </summary>
    public class ImageContentPart : MessageContentParts
    {
        /// <summary>
        /// The constructor
        /// </summary>
        public ImageContentPart() : base("image") { }

        /// <summary>
        /// The URL of the image.
        /// </summary>
        public string ImageUrl = string.Empty;
    }
}
