[book]
authors = ["Microsoft"]
language = "en"
multilingual = false
src = "src"
title = "Teams AI Library (v2)"

[build]
build-dir = "../docs"
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.theme]
pagetoc = false
sidebar-width = "250px"

[preprocessor.alerts]

[preprocessor.langtabs]
command = "mdbook-langtabs"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "http://github.com/microsoft/teams-ai"
additional-js = [
    "theme/mermaid/mermaid.min.js",
    "theme/mermaid/mermaid-init.js",
    "theme/langtabs/langtabs.js",
    "theme/lang/lang.js",
    "theme/pagetoc/pagetoc.js",
    "theme/custom.js"
]
additional-css = [
    "theme/variables.css",
    "theme/langtabs/langtabs.css",
    "theme/lang/lang.css",
    "theme/pagetoc/pagetoc.css",
    "theme/custom.css"
]

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false

[output.html.print]
enable = false
