#
# This workflow will build and run tests for the Microsoft.TeamsAI .NET SDK.
#

name: DOTNET Main

on:
  push:
    branches:
      - 'main'
    paths:
      - 'dotnet/**'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/dotnet-ci.yml

  publish:
    name: Publish
    needs: ci
    strategy:
      matrix:
        os: [windows-latest]
        dotnet-version: ['6.0', '7.0']
        configuration: [Release]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: dotnet/packages/Microsoft.TeamsAI/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Pack
        run: dotnet pack --output . --configuration ${{ matrix.configuration }} Microsoft.TeamsAI/Microsoft.TeamsAI.csproj

      - name: Publish
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/microsoft/index.json --skip-duplicate --no-symbols

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: nupkg-dotnet-${{ matrix.dotnet-version }}
          path: dotnet/packages/Microsoft.TeamsAI/*.nupkg
