#
# This workflow will build, run tests, and pack for the Microsoft.TeamsAI Python SDK.
#

name: Python PR

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'python/**'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/python-ci.yml
